Belém;Mangal das Garças;0;Parque ambiental com viveiros de aves e mirante.;Aberto das 00:00 - 18:00;
Belém;Mercado Ver-o-Peso;1;Feira ao ar livre de iguarias regionais e artesanato.;Aberto das 06:00 - 17:00;
Belém;Bar Point do Açaí;2;Espaço com música ao vivo e pratos à base de açaí.;Aberto das 18:00 - 01:00;
Belém;Estação das Docas (eventos);1;Shows e feiras culturais na área portuária revitalizada.;Aberto das 19:00 - 00:00;
Belém;Pissolati Café;3;Café acolhedor e sofisticado, perfeito para relaxar e apreciar bebidas artesanais e doces.;Aberto das 08:00 - 20:00;
Goiânia;Parque Flamboyant;0;Jardins, lago e pista de caminhada.;Aberto das 06:00 - 20:00;
Goiânia;Centro cultural Oscar Niemeyer;1;Centro de exposições e apresentações culturais.;Aberto das 10:00 - 18:00;
Goiânia;Bolshoi Pub;2;Bar temático com música ao vivo e drinks artesanais.;Aberto das 19:00 - 02:00;
Goiânia;Café Flor do Cerrado;3;Ambiente calmo com menu de cafés especiais.;Aberto das 08:00 - 20:00;
Porto Alegre;Parque Farroupilha (Redenção);0;Largo histórico com pista de caminhada e feiras.;Aberto das 05:00 - 22:00;
Porto Alegre;Mercado Público;1;Comércio de comidas típicas e artesanato.;Aberto das 07:00 - 19:00;
Porto Alegre;Festival de Jazz (Bola 8);2;Roda de jazz com músicos locais e convidados.;Aberto das 20:00 - 00:00;
Porto Alegre;Boulevard Café;3;Espaço calmo com cafés especiais e leitura.;Aberto das 08:00 - 22:00;
Salvador;Pelourinho;1;Centro histórico com casarões coloniais e igrejas.;Aberto das 09:00 - 17:00;
Salvador;Farol da Barra;0;Mirante e praia calma junto ao icônico farol.;Aberto das 08:00 - 19:00;
Salvador;Largo do Pelourinho (bloco);2;Shows de samba-reggae e festas de rua.;Aberto das 20:00 - 02:00;
Salvador;Café Literário da Fundação Casa de Jorge Amado;3;Espaço tranquilo para leitura e música ao vivo.;Aberto das 17:00 - 22:00;
Rio de Janeiro;Cristo Redentor / Parque da Tijuca;0;Trilha e vista panorâmica da cidade.;Aberto das 08:00 - 18:00;
Rio de Janeiro;Museu do Amanhã;1;Espaço de ciência e tecnologia interativa na zona portuária.;Aberto das 10:00 - 18:00;
Rio de Janeiro;Lapa (Arcos e bares);2;Sede dos tradicionais blocos de samba e bares.;Aberto das 18:00 - 03:00;
Rio de Janeiro;Praia de Copacabana (pôr do sol);3;Caminhada no calçadão ao entardecer.;Aberto das 17:00 - 19:00;